server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
    initialization-mode: always
    schema: classpath:import.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: INFO
    com:
      spring:
        ibatis: DEBUG